// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuSUQPLwPw47BfIisFDhUEexn-SBxRno',
    appId: '1:650422191742:android:23c4ecd3c1f62d921d3a2f',
    messagingSenderId: '650422191742',
    projectId: 'myproject-2-18848',
    databaseURL: 'https://myproject-2-18848-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-2-18848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYPv7MmFx2o9Yq9v8PnM7bUpvH7Z9TmE',
    appId: '1:650422191742:ios:4f093c807c7675d21d3a2f',
    messagingSenderId: '650422191742',
    projectId: 'myproject-2-18848',
    databaseURL: 'https://myproject-2-18848-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-2-18848.appspot.com',
    androidClientId: '650422191742-tds59b8jnh1c7qf5r0pc7ltirvm1lj5m.apps.googleusercontent.com',
    iosClientId: '650422191742-b9q24g8l4d3ntmr8jdii5mn8cmmon8ih.apps.googleusercontent.com',
    iosBundleId: 'com.app.project-2',
  );
}
